version: '3'
services:
  browser:
    env_file: 
      - ./app/.env.local
    build:
      context: docker/node
    container_name: $PROJECT_NAME-web
    restart: unless-stopped
    volumes:
      - ./app:/app
    ports:
      - "4000:4000"
    command: npm run start:browser
  server:
    env_file: 
      - ./app/.env.local
    build:
      context: docker/node
    container_name: $PROJECT_NAME-server
    restart: unless-stopped
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    command: npm run start:server

networks:
  default:
    external: 
      name: $NETWORK_NAME


