version: '3'
services:
  web:
    env_file: 
      - ./app/.env.local
    build:
      context: docker/node
    container_name: $PROJECT_NAME
    restart: unless-stopped
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    command: npm run dev

networks:
  default:
    external: 
      name: $NETWORK_NAME


