version: '3'
services:
  server:
    env_file: 
      - ./app/.env.local
    build:
      context: docker/node
    container_name: $PROJECT_NAME-server
    restart: unless-stopped
    volumes:
      - ./app:/app
      - ./docker/node/wait-for-it.sh:/wait-for-it.sh
    depends_on:
      - bd
    ports:
      - "3000:3000"
    entrypoint: /wait-for-it.sh -t 5 mysql:3306 -- 
    command: npm run start:all
  # browser:
  #   env_file: 
  #     - ./app/.env.local
  #   build:
  #     context: docker/node
  #   container_name: $PROJECT_NAME-browser
  #   restart: unless-stopped
  #   volumes:
  #     - ./app:/app
  #     - ./docker/node/wait-for-it.sh:/wait-for-it.sh
  #   ports:
  #     - "4000:4000"
  #   command: npm run browser:watch
  bd:
    env_file: 
      - ./app/.env.local
    build:
      context: docker/mysql
    image: $MYSQL_IMAGE
    container_name: $PROJECT_NAME-mysql
    restart: unless-stopped   
    ports:
      - '3306:3306'
    volumes: 
      - ./docker/mysql/data:/var/lib/mysql

networks:
  default:
    external: 
      name: $NETWORK_NAME


